updating tensor flow version to 1.9.0 and building using bazel

diff --git a/environments/1.0.0/keras-tensorflow/Dockerfile.py2 b/environments/1.0.0/keras-tensorflow/Dockerfile.py2
--- a/environments/1.0.0/keras-tensorflow/Dockerfile.py2
+++ b/environments/1.0.0/keras-tensorflow/Dockerfile.py2
@@ -5,14 +5,51 @@ MAINTAINER Datmo devs <dev@datmo.com>
 # Install datmo
 RUN pip install datmo
 
-ARG TENSORFLOW_VERSION=1.8.0
+ARG TENSORFLOW_VERSION=v1.9.0
 ARG KERAS_VERSION=2.1.6
 
-# Install TensorFlow
-RUN pip --no-cache-dir install tensorflow==${TENSORFLOW_VERSION}
+RUN git clone https://github.com/tensorflow/tensorflow.git --branch ${TENSORFLOW_VERSION} --single-branch
+WORKDIR /tensorflow
 
-# Install Keras
-RUN pip --no-cache-dir install git+git://github.com/fchollet/keras.git@${KERAS_VERSION}
+ENV CI_BUILD_PYTHON python
+
+# install mock for py2 build
+RUN python --version 2>&1 | grep 'Python 2' \
+    && pip --no-cache-dir install \
+        mock \
+        && rm -rf /pip_pkg \
+        && rm -rf /tmp/* \
+        && rm -rf /root/.cache \
+    || true
+
+# NOTE: This command uses special flags to build an optimized image for AWS machines.
+# This image might *NOT* work on other machines
+# Clean up pip wheel and Bazel cache when done.
+RUN tensorflow/tools/ci_build/builds/configured CPU \
+    bazel build -c opt --copt=-msse3 --copt=-msse4.1 --copt=-msse4.2 \
+        --copt=-mavx --copt=-mavx2 \
+        --copt=-mfma \
+        --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
+         \
+        --verbose_failures \
+        tensorflow/tools/pip_package:build_pip_package \
+    && bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip \
+    && pip --no-cache-dir install --upgrade /tmp/pip/tensorflow-*.whl \
+    && rm -rf /pip_pkg \
+    && rm -rf /tmp/* \
+    && rm -rf /root/.cache \
+    && cd / && rm -rf tensorflow
+
+WORKDIR /
+
+# Install Keras and tflearn
+# TODO: move h5py into dl-python base
+RUN pip --no-cache-dir install \
+        git+git://github.com/fchollet/keras.git@${KERAS_VERSION} \
+        tflearn==0.3.2 \
+    && rm -rf /pip_pkg \
+    && rm -rf /tmp/* \
+    && rm -rf /root/.cache
 
 # export port for tensorboard
 EXPOSE 6006
